/**
 * Created by ravikant on 19/11/14.
 */
function addUser(){
    var queryConfig=[
        {
            startNode:{nodeName:"School",nodeQueryAlias:"sc"},
            relation:null,
            endNode:null,
            returnAliases:["sc"],
            queryType:"search"
        },{
            startNode:{nodeName:"School",nodeQueryAlias:"sc",isNew:false},
            relation:{relationName:"USER_OF",relationQueryAlias:"sc_us"},
            endNode:{nodeName:"User",nodeQueryAlias:"us",isNew:true},
            returnAliases:["us"],
            queryType:"create"
        },
        {
            startNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            relation:{relationName:"CONTACT_OF",relationQueryAlias:"us_contact"},
            endNode:{nodeName:"Contact",nodeQueryAlias:"contact",isNew:true},
            returnAliases:["us","contact"],
            queryType:'create'
        },
        {
            startNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            relation:{relationName:"PRIMARY_ADDRESS_OF",relationQueryAlias:"us_pa"},
            endNode:{nodeName:"PrimaryAddress",nodeQueryAlias:"pa",isNew:true},
            returnAliases:["us","contact","pa"],
            queryType:'create'
        },
        {
            startNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            relation:{relationName:"SECONDARY_ADDRESS_OF",relationQueryAlias:"us_sa"},
            endNode:{nodeName:"SecondaryAddress",nodeQueryAlias:"sa",isNew:true},
            returnAliases:["us","contact","pa","sa"],
            queryType:'create'
        },
        {
            startNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            relation:{relationName:"SOCIAL_NETWORK_OF",relationQueryAlias:"us_socn"},
            endNode:{nodeName:"SocialNetwork",nodeQueryAlias:"socn",isNew:true},
            returnAliases:["us","contact","pa","sa","socn"],
            queryType:'create'
        },
        {
            startNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            relation:{relationName:"IMAGE_OF",relationQueryAlias:"us_img"},
            endNode:{nodeName:"Image",nodeQueryAlias:"img",isNew:true},
            returnAliases:["us","contact","pa","sa","socn","img"],
            queryType:'create'
        }
    ];
    return queryConfig;
}
module.exports.addUser=addUser;
function assocateClass(){
    var queryConfig=[
        {
            startNode:{nodeName:"School",nodeQueryAlias:"sc"},
            relation:{relationName:"CLASS_OF",relationQueryAlias:"sc_cl"},
            endNode:{nodeName:"Class",nodeQueryAlias:"cl"},
            returnAliases:["cl"],
            queryType:"search"
        },
        {
            startNode:{nodeName:"School",nodeQueryAlias:"sc"},
            relation:{relationName:"USER_OF",relationQueryAlias:"sc_us"},
            endNode:{nodeName:"User",nodeQueryAlias:"us"},
            returnAliases:["cl","us"],
            queryType:"search"
        },
        {
            startNode:{nodeName:"Class",nodeQueryAlias:"cl",isNew:false},
            relation:{relationName:"STUDENT_OF",relationQueryAlias:"cl_us"},
            endNode:{nodeName:"User",nodeQueryAlias:"us",isNew:false},
            returnAliases:["us","cl_us"],
            queryType:'create'
        }
    ];
    return queryConfig;
}
module.exports.assocateClass=assocateClass;